1. What does Pandas stand for?
    - Python Data Analysis
2. What are the 2 collections used in Pandas?
    - Pandas and NumPy
3. Name 4 things Pandas can do for us.
    - Data Cleansing, Data Fill, Data Visualization, Data Inspection
4. To permanently sort a DataFrame, which keyword should one use with the `df.sort()` method?
    - 
5. What is a CSV?
    - A data file
6. When cleaning data what values do we not like in our data?
    - 

In [9]:
# 7. Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method -- .reshape()

import numpy as np

a1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
shape = a1.reshape(2, 3, 2)
print(shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [10]:
# 8. Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20

a = np.linspace(0, 20, num = 6)
print(a)

[ 0.  4.  8. 12. 16. 20.]


In [14]:
# 9. Make a Deep Copy of the above array
import copy
a1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
a2 = copy.deepcopy(a1)
print(a1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [21]:
# 10. Concatenate these 3 arrays into a new array named 'newArray'...
import numpy as np
array1 = np.array([[25, 16]])
array2 = np.array([[11, 2], [13, 4]])
array3 = np.array([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((array1, array2, array3), axis = 0)
print(newArray)

[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [24]:
# 11. Sort 'newArray' in order into 'sortedArray'

sortedArray = np.argsort(newArray)
print(sortedArray)

[[1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [0 1]]


In [ ]:
# 12. Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.

a, b, c, d = shape
print(a)
print(b)
print(c)
print(d)

In [27]:
# 13. Combined and sort the following arrays into one called 'comboArray' ...

one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.concatenate((one, two, three))
print(np.sort(comboArray))

[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


In [ ]:
# 14. Take 'comboArray' and perform the following slicing activities:
# print sec1 - the 2nd element
print(comboArray[1])
# print sec2 - all elements from the 3rd element to the last
print(comboArray[4:])
# print sec3 - all elements from the 4th to the 14th elements
print(comboArray[5:15])
# print sec4 - the last 6 elements
print(comboArray[-6:])
# print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
print(comboArray[-19:-7])
# print sec6 - from #20 every even element to the end

# print sec7 - from the last element moving forward, every 5th element.



In [61]:
# 15. Using Series, create a DataFrame that looks like this:
#Ingredients	Quantity	Unit
#Flour	4	cups
#Milk	1	cup
#Eggs	2	large
#Spam	1	can
#Name: Dinner, dtype: object

Ingredients = pd.Series(['Flour', 'Milk', 'Eggs', 'Spam'], name = 'Ingredients')
Quantity = pd.Series(['4', '1', '2', '1'], name = 'Quantity')
Unit = pd.Series(['Cups', 'Cup', 'Large', 'Can'], name = 'Unit')

Dinner = pd.concat([Ingredients, Quantity, Unit], axis = 1)
Dinner

Ingredients Quantity   Unit
0       Flour        4   Cups
1        Milk        1    Cup
2        Eggs        2  Large
3        Spam        1    Can

In [64]:
# 16. Take this data and create a DataFrame named studentData:
studentData = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
    'Height': [5.1, 6.2, 5.1, 5.2],
    'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
    'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
    'Age': [21, 23, 24, 21],
    'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
    'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']}

studentData = pd.DataFrame(studentData)
studentData

Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket

In [ ]:
# 17. Add a new column to the DataFrame with the following deserts: ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

deserts = ["Ice Cream", "Cashew Fudge", "Waffels", "Carrot Halwa"]
studentData.insert(7, 'Deserts', deserts,True)
studentData

In [ ]:
# 18. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"

studentData.sort_values(by = ['Name'])
studentData

In [ ]:
# 19. Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:

df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])

In [ ]:
# 20. (A) Using Pandas, make your own .CSV file with data on vegetables and save it. (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.